In [1]:
import numpy as np

In [5]:
#Create a NumPy array from the list [10, 20, 30, 40] and print its shape, size, ndim, and dtype.

arr = np.array([10,20,30,40])
print("shape:",arr.shape)
print("Size:",arr.size)
print("dim:",arr.ndim)
print("type:",arr.dtype)

shape: (4,)
Size: 4
dim: 1
type: int64


In [11]:
#Create a 2D array [[1, 2, 3], [4, 5, 6]] and print its shape and number of dimensions

arr2d = np.array([[1,2,3],[4,5,6]])
print("shape:",arr2d.shape)
print("Dimension:",arr2d.ndim)

shape: (2, 3)
Dimension: 2


In [8]:
#Convert a list [1.5, 2.5, 3.5] into an integer NumPy array using dtype

arr = np.array([1.5,2.5,3,5],dtype=int)
arr

array([1, 2, 3, 5])

In [12]:
#Create a 3D NumPy array and print its ndim and size.

arr3d = np.arange(1,21).reshape(2,2,5)
print("size:",arr3d.size)
print("Dimension:",arr3d.ndim)

size: 20
Dimension: 3


In [13]:
#Create an array from 0 to 20 with step 2 using arange.
arr = np.arange(0,20,2)

arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
#Create 5 evenly spaced numbers between 1 and 10 using linspace

arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
#Create a 3×3 matrix filled with zeros.

mat = np.zeros(9).reshape(3,3)
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#Create a 2×4 matrix filled with ones.
mat = np.ones(8).reshape(2,4)
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
#Create a 3×3 matrix filled with value 7 using full.

mat = np.full(9,7).reshape(3,3)
mat

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [28]:
#Create a 4×4 identity matrix.

mat = np.identity(4,dtype=int)
mat

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [31]:
#Create a 3×3 matrix using eye with k=1.
mat = np.eye(3,3,1,dtype=int)
mat

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [34]:
#Create an empty array of shape (2,3) and print it.

arr = np.empty((2,3),dtype=int)
arr

array([[4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408]])

In [37]:
#Create an array from 1 to 12 and reshape it into (3,4).

arr = np.arange(1,13)

arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
#Convert a 2D array into 1D using ravel.

arr2d = np.arange(1,9).reshape(2,4)

arr2d.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
#Convert a 2D array into 1D using flatten.

arr2d = np.arange(1,9).reshape(2,4)

arr2d.flatten()


array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
#Reshape a 1D array of size 16 into a 4×4 matrix.

arr = np.arange(1,17)

arr.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
#Create two arrays a = [1,2,3] and b = [4,5,6] and concatenate them.

a = [1,2,3]
b = [4,5,6]

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [46]:
#Stack arrays a and b vertically.

a = [1,2,3]
b = [4,5,6]

np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
#Stack arrays a and b horizontally.

a = [1,2,3]
b = [4,5,6]

np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [50]:
#Use stack on a and b with axis=0 and axis=1 and observe output.

a = [1,2,3]
b = [4,5,6]

print(np.stack((a,b),axis=0))
print()
print(np.stack((a,b),axis=1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [52]:
#Create two 2×2 matrices and combine them using hstack.
mat1 = np.arange(1,5).reshape(2,2)
mat2 = np.arange(5,9).reshape(2,2)

np.hstack((mat1,mat2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [55]:
#Create two 2×2 matrices and combine them using vstack.

np.vstack((mat1,mat2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [56]:
#Create an array from 1 to 10 and split it into 2 equal parts.

arr = np.arange(1,11)

np.split(arr,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [57]:
#Split an array from 1 to 10 into 3 parts using split and observe error.

np.split(arr,3)

ValueError: array split does not result in an equal division

In [ ]:
#Split an array from 1 to 10 into 3 parts using array_split

arr = np.arange(1,11)

np.array_split(arr,3)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [110]:
#Create a 4×4 matrix and split it horizontally into 2 parts.

mat = np.arange(1,17).reshape(4,4)


print(np.hsplit(mat,2))

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


In [61]:
#Create a 4×4 matrix and split it vertically into 2 parts.

np.vsplit(mat,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [74]:
#Convert an integer array [1,2,3,4] into float using astype.

arr = np.array([1,2,3,4])

arr.astype(dtype=float)

array([1., 2., 3., 4.])

In [112]:
#Repeat each element of [1,2,3] twice using repeat

arr = np.array([1,2,3,4])

np.repeat(arr,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [114]:
#Flip the array [1,2,3,4].

arr = np.array([1,2,3,4])
np.flip(arr)

array([4, 3, 2, 1])

In [77]:
#Create a 2D array and transpose it using .T.

arr2d = np.arange(1,5).reshape(2,2)

arr2d.T

array([[1, 3],
       [2, 4]])

In [115]:
#Find unique elements from [1,2,2,3,4,4,5].

arr = np.array([1,2,2,3,4,4,5])

np.unique(arr)

array([1, 2, 3, 4, 5])

In [116]:
#Count frequency of unique elements from [1,2,2,3,3,3,4].

arr = np.array([1,2,2,3,3,3,4])

len(np.unique(arr))

4

In [82]:
#Create a 2D array and find unique values across the entire array

arr2d = np.array([[1,2,2,4,4],[2,3,4,5,6]])

np.unique(arr2d)

array([1, 2, 3, 4, 5, 6])

In [85]:
#Create an array using arange(1,13), reshape it to (3,4), transpose it, and flatten it.
arr = np.arange(1,13)
arr = arr.reshape(3,4)

arr_t = arr.T

arr_t.flatten()

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])

In [91]:
#Create two arrays using linspace, stack them, and split them into equal parts

arr1 = np.linspace(1,10,5)
arr2 = np.linspace(11,20,5)

stacked_arr = np.stack((arr1,arr2))

np.split(stacked_arr,2)

[array([[ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]]),
 array([[11.  , 13.25, 15.5 , 17.75, 20.  ]])]

In [117]:
#Create a matrix using ones, convert it to float, multiply by 5, and flip it

mat = np.ones(10).reshape(2,5)

mat = mat.astype(float)

mat = mat*5

np.flip(mat)

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [119]:
#Create an identity matrix, stack it with another identity matrix, and flatten the result.


arr1 = np.identity(2)
arr2 = np.identity(2)

arr = np.stack((arr1,arr2))

arr.flatten()

array([1., 0., 0., 1., 1., 0., 0., 1.])

In [121]:
#Create an array and use repeat with different repetition counts for each element.

elements = np.array([5,6,7])
repeats = [2, 3, 2]

np.repeat(elements, repeats)



array([5, 5, 6, 6, 6, 7, 7])

In [ ]:
#Create two 2D arrays and concatenate them along axis=0 and axis=1.

arr2d_1 = np.arange(1,9).reshape(2,4)
arr2d_2 = np.arange(9,17).reshape(2,4)

print(np.concatenate((arr2d_1,arr2d_2),axis=0))
print()
print(np.concatenate((arr2d_1,arr2d_2),axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


: 