In [1]:
#array

import numpy as np

In [3]:
li = [10,20,30,40,50]
np.array(li)

array([10, 20, 30, 40, 50])

In [53]:
l2 = [19,45,5,56, 29+6j]
arr = np.array(l2)
arr.ndim

1

In [54]:
l3 = ['str','stt']
arr = np.array(l3)

arr.dtype
arr.ndim

1

In [52]:
c = np.array([1,2,3,5,6,6+5j,7])
c.dtype
c.ndim

1

In [55]:
s = {1,2,3,4,5,6}
a = np.array(s)
a.dtype
a.ndim

0

In [57]:
t = (1,2,3,4,5,6)
a = np.array(t)
a.dtype
a.ndim

1

In [58]:
dic = {'a':1,'b':2}

arr = np.array(dic)
arr.dtype
arr.ndim

0

In [59]:
s = 'string'
ar = np.array(s)
ar.size
ar.ndim

0

In [9]:
"""" 
Priority of datatype
    if the array has the hetrogeneous elements, its converts the all elements datatype to the high priority datatype present in the list
low

    bool
    int
    float
    complex
    str
    object  (set, dict)

high

"""

'" \nPriority of datatype\n    if the array has the hetrogeneous elements, its converts the all elements datatype to the high priority datatype present in the list\nlow\n\n    bool\n    int\n    float\n    complex\n    str\n    object  (set, dict)\n\nhigh\n\n'

In [19]:
#2 dimensional array  (rows, colums)
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
#3d array   ---  (rows colunns elements)

arr2d = np.array([[1,2,3,'4'],[5,6,7,8]])
arr2d.dtype
arr2d.ndim
arr2d.size

8

In [28]:
arr2d.shape

(2, 4)

In [25]:
arr3d = np.array([arr2d,arr2d])

In [26]:
arr3d

array([[['1', '2', '3', '4'],
        ['5', '6', '7', '8']],

       [['1', '2', '3', '4'],
        ['5', '6', '7', '8']]], dtype='<U21')

In [27]:
arr3d.shape

(2, 2, 4)

In [158]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(13,25).reshape(3,4)

arr3d = np.array([a,b])
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [73]:
ae = np.arange(1,13).reshape(2,2,3)

ae

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
arr3_di = np.array([[[1,2,3,4],[6,7,8,9]],[[11,12,13,14],[16,17,18,19]]])

In [15]:
arr3_di

array([[[ 1,  2,  3,  4],
        [ 6,  7,  8,  9]],

       [[11, 12, 13, 14],
        [16, 17, 18, 19]]])

In [16]:
arr2_d = np.array([[1,2,3,4],[5,6+2j,7,8]])

In [17]:
np.array([arr2_d,arr2d])     # if any of the element present in array with other it will convert the entire array to the priority datatype

array([[[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
        [5.+0.j, 6.+2.j, 7.+0.j, 8.+0.j]],

       [[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
        [5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j]]])

In [18]:
#property of the array

## property of the array 

## shape

In [74]:
#2d array
arr2d.shape

(2, 4)

In [75]:
arr.shape      # for 1 d array shape returns the number of element present in the array

(2, 3, 4)

In [21]:
arr3d.shape

(2, 2, 4)

## ndim

In [22]:

#number of the dimension present in the array
arr.ndim

1

In [23]:
arr2d.ndim

2

In [24]:
arr3d.ndim

3

## size

In [25]:
#returns the size of the array

In [26]:
arr.size

5

In [27]:
arr2d.size    # (rows * columns)

8

In [28]:
arr3d.size    # (rows * columns * element)

16

## dtype

In [29]:
arr.dtype

dtype('complex128')

In [30]:
arr2d.dtype

dtype('int64')

In [31]:
arr3d.dtype

dtype('int64')

In [32]:
arr3_di.dtype

dtype('int64')

In [33]:
#practice

In [77]:
string_arr = ['a','b','c',{1,2,3,4}]

b = np.array(string_arr)
b

array(['a', 'b', 'c', {1, 2, 3, 4}], dtype=object)

In [78]:
b.dtype

dtype('O')

In [79]:
b.size

4

In [80]:
b.ndim

1

In [81]:
arr1 = [i for i in range(1,100)]

In [82]:
np.array(arr1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [83]:
arr3 = [i for i in range(1,173)]
np.array(arr3).reshape(43,1,4)

array([[[  1,   2,   3,   4]],

       [[  5,   6,   7,   8]],

       [[  9,  10,  11,  12]],

       [[ 13,  14,  15,  16]],

       [[ 17,  18,  19,  20]],

       [[ 21,  22,  23,  24]],

       [[ 25,  26,  27,  28]],

       [[ 29,  30,  31,  32]],

       [[ 33,  34,  35,  36]],

       [[ 37,  38,  39,  40]],

       [[ 41,  42,  43,  44]],

       [[ 45,  46,  47,  48]],

       [[ 49,  50,  51,  52]],

       [[ 53,  54,  55,  56]],

       [[ 57,  58,  59,  60]],

       [[ 61,  62,  63,  64]],

       [[ 65,  66,  67,  68]],

       [[ 69,  70,  71,  72]],

       [[ 73,  74,  75,  76]],

       [[ 77,  78,  79,  80]],

       [[ 81,  82,  83,  84]],

       [[ 85,  86,  87,  88]],

       [[ 89,  90,  91,  92]],

       [[ 93,  94,  95,  96]],

       [[ 97,  98,  99, 100]],

       [[101, 102, 103, 104]],

       [[105, 106, 107, 108]],

       [[109, 110, 111, 112]],

       [[113, 114, 115, 116]],

       [[117, 118, 119, 120]],

       [[121, 122, 123, 124]],

       [

## reshape

In [84]:
count = 0
n = 249
for  i in range(1,250):
    if n % i == 0:
        count += 1
if count == 2:
    print('prime')
else:
    print('not prime')

not prime


In [86]:
import math

a = math.factorial(249)
a

12931425043636430929283258208097473883979374870695122666991769708451294990220444837955271661484112797803714029412757731706923726851235963291164121116285127686706108960757058932872164745044027331701460534715756358279742854120700162052715040308991732261609356024659302208995277746290344229596890565019331928819396550887106602565107435228612515915110691807655963377509914810356691893020601132967149282632753928249914330639235395302195200000000000000000000000000000000000000000000000000000000000

In [87]:
b = math.factorial(247)
result = a/(math.factorial(2)*b)

In [88]:
result

30876.0

In [45]:
math.comb(249,2)

30876

In [46]:
math.comb(6,2)

15

In [89]:
arr = np.array(list(range(1,500,2)))

In [90]:
len(arr)

250

In [92]:
a = arr.reshape(2,125)
a

array([[  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
         27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
         53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
         79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
        105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
        131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
        157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
        183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207,
        209, 211, 213, 215, 217, 219, 221, 223, 225, 227, 229, 231, 233,
        235, 237, 239, 241, 243, 245, 247, 249],
       [251, 253, 255, 257, 259, 261, 263, 265, 267, 269, 271, 273, 275,
        277, 279, 281, 283, 285, 287, 289, 291, 293, 295, 297, 299, 301,
        303, 305, 307, 309, 311, 313, 315, 317, 319, 321, 323, 325, 327,
        329, 331, 333, 335, 337, 339, 341, 343, 345, 347, 349, 351, 353,
  

In [94]:
a[1][56].item()

363

In [95]:
b = arr.reshape(2,25,5)

In [96]:
b

array([[[  1,   3,   5,   7,   9],
        [ 11,  13,  15,  17,  19],
        [ 21,  23,  25,  27,  29],
        [ 31,  33,  35,  37,  39],
        [ 41,  43,  45,  47,  49],
        [ 51,  53,  55,  57,  59],
        [ 61,  63,  65,  67,  69],
        [ 71,  73,  75,  77,  79],
        [ 81,  83,  85,  87,  89],
        [ 91,  93,  95,  97,  99],
        [101, 103, 105, 107, 109],
        [111, 113, 115, 117, 119],
        [121, 123, 125, 127, 129],
        [131, 133, 135, 137, 139],
        [141, 143, 145, 147, 149],
        [151, 153, 155, 157, 159],
        [161, 163, 165, 167, 169],
        [171, 173, 175, 177, 179],
        [181, 183, 185, 187, 189],
        [191, 193, 195, 197, 199],
        [201, 203, 205, 207, 209],
        [211, 213, 215, 217, 219],
        [221, 223, 225, 227, 229],
        [231, 233, 235, 237, 239],
        [241, 243, 245, 247, 249]],

       [[251, 253, 255, 257, 259],
        [261, 263, 265, 267, 269],
        [271, 273, 275, 277, 279],
        [281, 283,

In [100]:
b[0][16][2].item()

165

In [101]:
arr.reshape(-1)    # -1 convert the n dim to the 1 dim

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207,
       209, 211, 213, 215, 217, 219, 221, 223, 225, 227, 229, 231, 233,
       235, 237, 239, 241, 243, 245, 247, 249, 251, 253, 255, 257, 259,
       261, 263, 265, 267, 269, 271, 273, 275, 277, 279, 281, 283, 285,
       287, 289, 291, 293, 295, 297, 299, 301, 303, 305, 307, 309, 311,
       313, 315, 317, 319, 321, 323, 325, 327, 329, 331, 333, 335, 337,
       339, 341, 343, 345, 347, 349, 351, 353, 355, 357, 359, 36

In [107]:
arrr = np.arange(1,13).reshape(3,4)
arrr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [111]:
arrr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [113]:
arrr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## flatten


In [102]:
# used to convert the n dim to 1 dim
a.flatten()

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207,
       209, 211, 213, 215, 217, 219, 221, 223, 225, 227, 229, 231, 233,
       235, 237, 239, 241, 243, 245, 247, 249, 251, 253, 255, 257, 259,
       261, 263, 265, 267, 269, 271, 273, 275, 277, 279, 281, 283, 285,
       287, 289, 291, 293, 295, 297, 299, 301, 303, 305, 307, 309, 311,
       313, 315, 317, 319, 321, 323, 325, 327, 329, 331, 333, 335, 337,
       339, 341, 343, 345, 347, 349, 351, 353, 355, 357, 359, 36

In [103]:
a

array([[  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
         27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
         53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
         79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
        105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
        131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
        157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
        183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207,
        209, 211, 213, 215, 217, 219, 221, 223, 225, 227, 229, 231, 233,
        235, 237, 239, 241, 243, 245, 247, 249],
       [251, 253, 255, 257, 259, 261, 263, 265, 267, 269, 271, 273, 275,
        277, 279, 281, 283, 285, 287, 289, 291, 293, 295, 297, 299, 301,
        303, 305, 307, 309, 311, 313, 315, 317, 319, 321, 323, 325, 327,
        329, 331, 333, 335, 337, 339, 341, 343, 345, 347, 349, 351, 353,
  

## ravel

In [104]:
# used to convert the n dim to 1 dim
a.ravel()

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207,
       209, 211, 213, 215, 217, 219, 221, 223, 225, 227, 229, 231, 233,
       235, 237, 239, 241, 243, 245, 247, 249, 251, 253, 255, 257, 259,
       261, 263, 265, 267, 269, 271, 273, 275, 277, 279, 281, 283, 285,
       287, 289, 291, 293, 295, 297, 299, 301, 303, 305, 307, 309, 311,
       313, 315, 317, 319, 321, 323, 325, 327, 329, 331, 333, 335, 337,
       339, 341, 343, 345, 347, 349, 351, 353, 355, 357, 359, 36

In [105]:
a

array([[  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
         27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
         53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
         79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
        105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
        131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
        157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
        183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207,
        209, 211, 213, 215, 217, 219, 221, 223, 225, 227, 229, 231, 233,
        235, 237, 239, 241, 243, 245, 247, 249],
       [251, 253, 255, 257, 259, 261, 263, 265, 267, 269, 271, 273, 275,
        277, 279, 281, 283, 285, 287, 289, 291, 293, 295, 297, 299, 301,
        303, 305, 307, 309, 311, 313, 315, 317, 319, 321, 323, 325, 327,
        329, 331, 333, 335, 337, 339, 341, 343, 345, 347, 349, 351, 353,
  

## arange

In [57]:
np.arange(1,45.90,1.5)    #used to generate the sequenece of number , unlike python range it has array structure, possible to generate float step

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. , 11.5, 13. , 14.5, 16. ,
       17.5, 19. , 20.5, 22. , 23.5, 25. , 26.5, 28. , 29.5, 31. , 32.5,
       34. , 35.5, 37. , 38.5, 40. , 41.5, 43. , 44.5])

In [114]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linspace

In [59]:
np.linspace(1,10)   # by deafault divides in 50 elemnets

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [60]:
np.linspace(1,10,10)    # it divedes x and y into given step in equaly

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [117]:
np.linspace(1,12,60)

array([ 1.        ,  1.18644068,  1.37288136,  1.55932203,  1.74576271,
        1.93220339,  2.11864407,  2.30508475,  2.49152542,  2.6779661 ,
        2.86440678,  3.05084746,  3.23728814,  3.42372881,  3.61016949,
        3.79661017,  3.98305085,  4.16949153,  4.3559322 ,  4.54237288,
        4.72881356,  4.91525424,  5.10169492,  5.28813559,  5.47457627,
        5.66101695,  5.84745763,  6.03389831,  6.22033898,  6.40677966,
        6.59322034,  6.77966102,  6.96610169,  7.15254237,  7.33898305,
        7.52542373,  7.71186441,  7.89830508,  8.08474576,  8.27118644,
        8.45762712,  8.6440678 ,  8.83050847,  9.01694915,  9.20338983,
        9.38983051,  9.57627119,  9.76271186,  9.94915254, 10.13559322,
       10.3220339 , 10.50847458, 10.69491525, 10.88135593, 11.06779661,
       11.25423729, 11.44067797, 11.62711864, 11.81355932, 12.        ])

## zeros

In [118]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [119]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [120]:
np.zeros(10,dtype='complex')

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j])

In [64]:
np.zeros((2,5),dtype='int')    #2d array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [65]:
np.zeros((2,5,5),dtype='int')  #3d array

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [66]:
np.zeros(10,dtype=set)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=object)

## ones



In [67]:
np.ones(10,dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [68]:
np.ones(10,dtype='complex')

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j,
       1.+0.j, 1.+0.j])

In [69]:
np.ones((2,4),dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [70]:
np.ones((2,4,5),dtype='int')

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

## full

In [1]:
import numpy as np

np.full(8,2)

array([2, 2, 2, 2, 2, 2, 2, 2])

In [2]:
np.full((2,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [3]:
np.full((2,3,4),6)

array([[[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]],

       [[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]]])

## identity matrix

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(4,dtype=set)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=object)

## eye

In [ ]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [ ]:
np.eye(4,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
np.eye(4,4,k=1,dtype=int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

## empty

In [ ]:
np.empty(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.empty((4,4),dtype=int)

array([[4607182418800017408, 4611686018427387904, 4613937818241073152,
        4616189618054758400],
       [4617315517961601024, 4618441417868443648, 4619567317775286272,
        4620693217682128896],
       [4607182418800017408, 4611686018427387904, 4613937818241073152,
        4616189618054758400],
       [4617315517961601024, 4618441417868443648, 4619567317775286272,
        4620693217682128896]])

## Array manipulation method

## 1. reshape

In [122]:
import numpy as np
arr = np.arange(1,41,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [123]:
arr.size

20

In [124]:
arr.reshape(5,4)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31],
       [33, 35, 37, 39]])

In [125]:
# convert to 3d array

a = arr.reshape(2,2,5)   # it returns the new array, instead of modify the existing array
a

array([[[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]],

       [[21, 23, 25, 27, 29],
        [31, 33, 35, 37, 39]]])

In [126]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

## 2.flatten

In [127]:
arr = np.arange(1,41,2).reshape(5,4)

In [128]:
arr

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31],
       [33, 35, 37, 39]])

In [129]:
arr.flatten()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

## 3.revel

In [130]:
arr.ravel()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [131]:
arr.ravel('A')

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [132]:
arr.ravel('F')

array([ 1,  9, 17, 25, 33,  3, 11, 19, 27, 35,  5, 13, 21, 29, 37,  7, 15,
       23, 31, 39])

In [133]:
arr.ravel('C')

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [134]:
arr.ravel('K')

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [135]:
arr

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31],
       [33, 35, 37, 39]])

## 4. astype

In [136]:
arr = np.arange(1,41,2)

In [137]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [138]:
arr.dtype

dtype('int64')

In [139]:
arr.astype(complex)

array([ 1.+0.j,  3.+0.j,  5.+0.j,  7.+0.j,  9.+0.j, 11.+0.j, 13.+0.j,
       15.+0.j, 17.+0.j, 19.+0.j, 21.+0.j, 23.+0.j, 25.+0.j, 27.+0.j,
       29.+0.j, 31.+0.j, 33.+0.j, 35.+0.j, 37.+0.j, 39.+0.j])

In [140]:
arr.astype(str)

array(['1', '3', '5', '7', '9', '11', '13', '15', '17', '19', '21', '23',
       '25', '27', '29', '31', '33', '35', '37', '39'], dtype='<U21')

In [141]:
arr.astype(set)

array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39], dtype=object)

In [142]:
arr.astype(float)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39.])

In [143]:
arr2d = np.arange(1,41,2).reshape(4,5)

In [144]:
arr2d.astype(complex)

array([[ 1.+0.j,  3.+0.j,  5.+0.j,  7.+0.j,  9.+0.j],
       [11.+0.j, 13.+0.j, 15.+0.j, 17.+0.j, 19.+0.j],
       [21.+0.j, 23.+0.j, 25.+0.j, 27.+0.j, 29.+0.j],
       [31.+0.j, 33.+0.j, 35.+0.j, 37.+0.j, 39.+0.j]])

In [ ]:
arr3d = np.arange(1,41,2).reshape(2,2,5)

In [ ]:
arr3d.astype(complex)

array([[[ 1.+0.j,  3.+0.j,  5.+0.j,  7.+0.j,  9.+0.j],
        [11.+0.j, 13.+0.j, 15.+0.j, 17.+0.j, 19.+0.j]],

       [[21.+0.j, 23.+0.j, 25.+0.j, 27.+0.j, 29.+0.j],
        [31.+0.j, 33.+0.j, 35.+0.j, 37.+0.j, 39.+0.j]]])

## 5. repeat()

In [147]:
arr.repeat(3)   #used to repeat the element n time

array([ 1,  1,  1,  3,  3,  3,  5,  5,  5,  7,  7,  7,  9,  9,  9, 11, 11,
       11, 13, 13, 13, 15, 15, 15, 17, 17, 17, 19, 19, 19, 21, 21, 21, 23,
       23, 23, 25, 25, 25, 27, 27, 27, 29, 29, 29, 31, 31, 31, 33, 33, 33,
       35, 35, 35, 37, 37, 37, 39, 39, 39])

In [148]:
arr2d

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [149]:
np.repeat(arr2d,3)   # it converts the 2d array to 1d array when repeat used

array([ 1,  1,  1,  3,  3,  3,  5,  5,  5,  7,  7,  7,  9,  9,  9, 11, 11,
       11, 13, 13, 13, 15, 15, 15, 17, 17, 17, 19, 19, 19, 21, 21, 21, 23,
       23, 23, 25, 25, 25, 27, 27, 27, 29, 29, 29, 31, 31, 31, 33, 33, 33,
       35, 35, 35, 37, 37, 37, 39, 39, 39])

In [150]:
np.repeat(arr3d,4)

array(['1', '1', '1', '1', '2', '2', '2', '2', '3', '3', '3', '3', '4',
       '4', '4', '4', '5', '5', '5', '5', '6', '6', '6', '6', '7', '7',
       '7', '7', '8', '8', '8', '8', '1', '1', '1', '1', '2', '2', '2',
       '2', '3', '3', '3', '3', '4', '4', '4', '4', '5', '5', '5', '5',
       '6', '6', '6', '6', '7', '7', '7', '7', '8', '8', '8', '8'],
      dtype='<U21')

## 6. T  (Trasnpose)

In [151]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [152]:
arr.T    # on 1 d array nothing happens

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [153]:
arr2d

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [154]:
arr2d.T    # convets the rows to the column and column to rows


array([[ 1, 11, 21, 31],
       [ 3, 13, 23, 33],
       [ 5, 15, 25, 35],
       [ 7, 17, 27, 37],
       [ 9, 19, 29, 39]])

In [159]:
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [160]:
arr3d.T    #uses the element instead of the rows and column

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

## 7. flip

In [161]:
#flip is used to reverse the array
arr = np.arange(1,13)

In [165]:
np.flip(arr)

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [164]:
np.flip(arr,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [166]:
arr2d

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [170]:
np.flip(arr2d)

array([[39, 37, 35, 33, 31],
       [29, 27, 25, 23, 21],
       [19, 17, 15, 13, 11],
       [ 9,  7,  5,  3,  1]])

In [171]:
np.flip(arr2d)

array([[39, 37, 35, 33, 31],
       [29, 27, 25, 23, 21],
       [19, 17, 15, 13, 11],
       [ 9,  7,  5,  3,  1]])

In [172]:
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [176]:
np.flip(arr3d)

array([[[24, 23, 22, 21],
        [20, 19, 18, 17],
        [16, 15, 14, 13]],

       [[12, 11, 10,  9],
        [ 8,  7,  6,  5],
        [ 4,  3,  2,  1]]])

## 8. delete

In [ ]:
#used to remove the element based on the index value

In [177]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [181]:
np.delete(arr,0)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [182]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [183]:
arr2d

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [184]:
np.delete(arr2d,(1,1))    # delete and convert the array to teh 1 d array

array([ 1,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39])

## 9. unique

In [185]:
import numpy as np

arr = np.array([1,2,2,3,4,2,5,9,6])

In [186]:
arr

array([1, 2, 2, 3, 4, 2, 5, 9, 6])

In [189]:
np.unique(arr,axis=0)   # also sort the array asending order

array([1, 2, 3, 4, 5, 6, 9])

In [194]:
arr2d = np.array([[1,1,2,2,3,4,4],[5,5,6,7,8,8,6]])
arr2d


array([[1, 1, 2, 2, 3, 4, 4],
       [5, 5, 6, 7, 8, 8, 6]])

In [199]:
np.unique(arr2d)     #converts to the one dimensional

array([1, 2, 3, 4, 5, 6, 7, 8])

## 10. concatenate

In [200]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([2,3,5,8,9])

In [ ]:
np.concatenate((arr,arr2))  # for 1d if axis = 1 if returns the error

array([1, 2, 3, 4, 5, 2, 3, 5, 8, 9])

array([[1, 1, 2, 2, 3, 4, 4],
       [5, 5, 6, 7, 8, 8, 6]])

In [213]:
#for 2d array

arr2d = np.arange(1,9).reshape(2,4)
arr2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [214]:
arr2d_2 = np.array([9,10,11,12,13,14,15,16]).reshape(2,4)
arr2d_2

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [217]:
np.concatenate((arr2d_2,arr2d)) 

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [219]:
np.concatenate((arr2d_2,arr2d),axis=1)     #shape should be same, by deafaukt the  axis = 0 , means rows wise concatenation

array([[ 9, 10, 11, 12,  1,  2,  3,  4],
       [13, 14, 15, 16,  5,  6,  7,  8]])

In [90]:
np.concatenate((arr2d,arr2d_2),axis=1)    #axis = 1 is the column operation

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [220]:
#for 3d array

arr3d_1 = np.arange(1,21).reshape(2,2,5)
arr3d_2 = np.arange(21,41).reshape(2,2,5)

In [221]:
arr3d_1

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [222]:
arr3d_2

array([[[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]]])

In [223]:
np.concatenate((arr3d_1,arr3d_2))    #the shape should be the same

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]]])

In [224]:
np.concatenate((arr3d_1,arr3d_2),axis=1) 

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]]])

## 11.stack

In [236]:
np.stack((arr,arr2),axis=1)     #size should be equal

array([[1, 2],
       [2, 3],
       [3, 5],
       [4, 8],
       [5, 9]])

In [232]:
np.vstack((arr,arr2))

array([[1, 2, 3, 4, 5],
       [2, 3, 5, 8, 9]])

In [233]:
np.hstack((arr,arr2))

array([1, 2, 3, 4, 5, 2, 3, 5, 8, 9])

In [110]:
arr2d_2
arr2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [227]:
arr2d = np.arange(1,13).reshape(3,4)
arr2d_2 = np.arange(13,25).reshape(3,4)

In [230]:
np.stack((arr2d,arr2d_2))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [231]:
#vstack

np.stack((arr2d,arr2d_2))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [237]:
np.hstack((arr2d,arr2d_2))

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

# 1.randint

In [239]:
from numpy import random

In [5]:
random.randint(5)  #give the single element from 0 to n

1

In [244]:
random.randint(2,3)  #give the single value from start and end

2

In [245]:
random.randn(5)

array([ 0.17777863, -0.3862529 ,  0.48070034,  0.92126237, -0.84423572])

In [264]:
random.randn(2,4)

array([[ 0.25861467,  0.0915898 , -1.31587961,  0.01236975],
       [ 1.73638161, -0.49094914, -0.34268769,  0.84843001]])

In [266]:
random.choice([1,2,3,4,5],9)

array([3, 1, 5, 2, 3, 2, 2, 4, 4])

## interview q of numpy

1. what is dff betwween numpy array and list
2. what do shape,size, ndim represent in numpy array
3. what is dtype and why does numpy enforce a single datatype in a array
4. diff between arange and linspace, when to use each of them
5. what is diff between zeros, ones, full, empty
6. why does empty contain random values
7. diff between identity and eye, what is the role of k in eye
8. what happens if you try reshape an array into incompetable shape
9. Diff between ravel in flatten which one affects the original array
10. diff between contcatenate and stack
11. diff between hstack, vstack and stack
12. what happens try to stack arrays of diff shapes
13. what is the diff between split and array split 
14. diff between hsplit and vsplit
15. what is astype and what happens when converting float to int
16. how does tranpose behave for 1D vs 2D
17. what is the use of unique()
18. can unique() work on multi dim array, if yes how
19. what does the axis mean in numpy operation
20. what is the diff between dim and axis
21. what is diff rand and randint
22. when to use randn and rand

In [289]:
arr = np.random.randint(1,13,12).reshape(3,4)
arr2 = np.arange(13,25).reshape(3,4)
arr

array([[ 6,  9,  4,  2],
       [ 7, 12,  8,  8],
       [ 5,  3,  7, 11]], dtype=int32)

In [282]:
arr2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [283]:
arr+arr2

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [284]:
arr*arr2

array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

In [285]:
arr2-arr

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [292]:
arr = arr.reshape(-1)
arr

array([ 6,  9,  4,  2,  7, 12,  8,  8,  5,  3,  7, 11], dtype=int32)

In [293]:
np.argsort(arr)

array([ 3,  9,  2,  8,  0, 10,  4,  7,  6,  1, 11,  5])

In [296]:
arr[np.argsort(arr)]

array([ 2,  3,  4,  5,  6,  7,  7,  8,  8,  9, 11, 12], dtype=int32)