In [1]:
import numpy as np

In [2]:
a = np.array([i for i in range(10,101,10)])
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [3]:
b = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]
])

T = np.arange(1,25).reshape(2,3,4)

In [4]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [5]:
T

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [6]:
#extract the first 4 element from a

a[:4]

array([10, 20, 30, 40])

In [7]:
#extract the last three elements from a using negative indexing

a[-1:-4:-1]

array([100,  90,  80])

In [8]:
#extract every other element from a (step 2)

a[::2]

array([10, 30, 50, 70, 90])

In [9]:
#reverser the array a using slicing only

a[::-1]

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [10]:
#extract element form index 2 upto index 7 from a

a[2:7]

array([30, 40, 50, 60, 70])

In [11]:
#what does a[-3:8] return ?
a[-3:8]

array([80])

In [12]:
#extract every element from odd index from a

a[1::2]

array([ 20,  40,  60,  80, 100])

In [13]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
#extract the entire second row of the B

b[1:2:,::]

array([[5, 6, 7, 8]])

In [15]:
import copy

In [16]:
a = [10,20,30,[10,20,30]]

b = copy.copy(a)

In [17]:
b

[10, 20, 30, [10, 20, 30]]

In [18]:
b[3][1] = 90

In [19]:
b

[10, 20, 30, [10, 90, 30]]

In [20]:
a

[10, 20, 30, [10, 90, 30]]

In [21]:
#deep copy
c = [10,20,30,[10,20,30]]

d = copy.deepcopy(c)

In [22]:
d[3][1] = 90

In [23]:
d

[10, 20, 30, [10, 90, 30]]

In [24]:
c

[10, 20, 30, [10, 20, 30]]

In [25]:
import numpy as np
a = np.arange(1,17).reshape(4,4)

In [26]:
a.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [27]:
a = np.arange(1,13)
b = a.reshape(3,4)

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
b[0][0] = 21323

In [29]:
print(a)
print(b)

[21323     2     3     4     5     6     7     8     9    10    11    12]
[[21323     2     3     4]
 [    5     6     7     8]
 [    9    10    11    12]]


In [30]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(3,2)

In [31]:
print(a)
print(b)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [32]:
a+b

ValueError: operands could not be broadcast together with shapes (6,) (3,2) 

In [ ]:
import numpy as np

In [ ]:
a = [[1,2,3,4],[2,3,4,5]]

In [ ]:
b = np.array(a)
b

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [ ]:
c = b.flatten()
c

array([1, 2, 3, 4, 2, 3, 4, 5])

In [ ]:
c[0] = 9.0

In [ ]:
print(b)
print(c)

[[1 2 3 4]
 [2 3 4 5]]
[9 2 3 4 2 3 4 5]


In [ ]:
b

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [ ]:
d = b.astype(float)

In [ ]:
print(d.dtype)
print(b.dtype)

float64
int64


In [ ]:
b.astype(complex)

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j]])

In [ ]:
b.dtype

dtype('int64')

In [ ]:
#1d using the arange
import numpy as np
a = np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
b = np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c = np.sqrt(b)

In [ ]:
c[0][0] = 10
c

array([[10.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712],
       [ 3.        ,  3.16227766,  3.31662479,  3.46410162]])

In [ ]:
c = b.T
c

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
c[0][2] = 17
c

array([[15,  5, 17],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
b

array([[15,  2,  3,  4],
       [ 5,  6,  7,  8],
       [17, 10, 11, 12]])

In [ ]:
#properties of arrayb
b.dtype

dtype('int64')

In [ ]:
b.size

12

In [ ]:
b.ndim

2

In [ ]:
b.shape

(3, 4)

In [ ]:
b.reshape(4,-1)

array([[15,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 17],
       [10, 11, 12]])

In [ ]:
b.dtype

dtype('int64')

In [ ]:
#linspace

a = np.linspace(1,25,25)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.])

In [ ]:
a = np.zeros(6,dtype=int)
a

array([0, 0, 0, 0, 0, 0])

In [ ]:
a.dtype

dtype('int64')

In [38]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
a.dtype

dtype('float64')

In [41]:
#empty

a = np.empty((2,4),dtype=int)
a

array([[  0,   0,   0,   0],
       [  0, 336,   0,   0]])

In [44]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
a.dtype

dtype('float64')

In [47]:
a = np.eye(2,3,1)
a

array([[0., 1., 0.],
       [0., 0., 1.]])

In [48]:
a.dtype

dtype('float64')

In [52]:
#reshape

a = np.arange(1,13)

b = a.reshape(3,4)

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:
b[0][0] = 90

In [54]:
print(a)
print(b)

[90  2  3  4  5  6  7  8  9 10 11 12]
[[90  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [65]:
b = np.repeat(a,2)
print(a)
print(b)

[90  2  3  4  5  6  7  8  9 10 11 12]
[90 90  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10 10 11 11 12 12]


In [66]:
b[0] = 9000

In [67]:
print(a)
print(b)

[90  2  3  4  5  6  7  8  9 10 11 12]
[9000   90    2    2    3    3    4    4    5    5    6    6    7    7
    8    8    9    9   10   10   11   11   12   12]


In [71]:
a = np.arange(1,13).reshape(3,4)
b = a.T

print(a)
print()
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [72]:
b[0][0] = 900

In [73]:
print(a)
print(b)

[[900   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[900   5   9]
 [  2   6  10]
 [  3   7  11]
 [  4   8  12]]


In [74]:
a

array([[900,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [76]:
b = np.flip(a)
b

array([[ 12,  11,  10,   9],
       [  8,   7,   6,   5],
       [  4,   3,   2, 900]])

In [77]:
b[0][0] = 23

In [78]:
print(a)
print(b)

[[900   2   3   4]
 [  5   6   7   8]
 [  9  10  11  23]]
[[ 23  11  10   9]
 [  8   7   6   5]
 [  4   3   2 900]]


In [79]:
np.delete(a,90)

IndexError: index 90 is out of bounds for axis 0 with size 12

In [80]:
a

array([[900,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  23]])

In [81]:
b = np.unique(a)

In [83]:
print(a)

print(b)

[[900   2   3   4]
 [  5   6   7   8]
 [  9  10  11  23]]
[  2   3   4   5   6   7   8   9  10  11  23 900]


In [86]:
b[0] = 90

In [88]:
print(a)
print(b)

[[900   2   3   4]
 [  5   6   7   8]
 [  9  10  11  23]]
[ 90   3   4   5   6   7   8   9  10  11  23 900]


In [ ]:
a = np.arange(1,6)
b = np.arange(9,12)

c = np.concatenate((a,b))

In [91]:
print(a)
print(b)
print(c)

[1 2 3 4 5]
[ 9 10 11]
[ 1  2  3  4  5  9 10 11]


In [92]:
c[0] = 90

In [93]:
print(a)
print(b)
print(c)

[1 2 3 4 5]
[ 9 10 11]
[90  2  3  4  5  9 10 11]


In [97]:
c = np.concatenate((a,b),axis=0)
c

array([ 1,  2,  3,  4,  5,  9, 10, 11])

In [98]:
c = np.concatenate((a,b),axis=1)
c

AxisError: axis 1 is out of bounds for array of dimension 1

In [106]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(9,12).reshape(1,3)

In [107]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]]


In [109]:
c = np.concatenate((a,b))
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11]])

In [110]:
c = np.concatenate((a,b),axis=0)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11]])

In [111]:
c = np.concatenate((a,b),axis=1)
c

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [114]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(9,15).reshape(2,3)

In [115]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [117]:
c = np.concatenate((a,b),axis=0)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11],
       [12, 13, 14]])

In [118]:
c = np.concatenate((a,b),axis=1)
c

array([[ 1,  2,  3,  9, 10, 11],
       [ 4,  5,  6, 12, 13, 14]])

In [119]:
a = np.arange(1,13).reshape(2,3,2)
b = np.arange(13,25).reshape(2,3,2)

In [122]:
print(a)
print()
print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[[[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [124]:
c = np.concatenate((a,b))
c

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [125]:
c = np.concatenate((a,b),axis=1)
c

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [13, 14],
        [15, 16],
        [17, 18]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [130]:
#stack

a = np.arange(1,13)
b = np.arange(13,25)

In [131]:
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[13 14 15 16 17 18 19 20 21 22 23 24]


In [133]:
c = np.stack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [134]:
c = np.stack((a,b),axis=0)
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [135]:
c = np.stack((a,b),axis=1)
c

array([[ 1, 13],
       [ 2, 14],
       [ 3, 15],
       [ 4, 16],
       [ 5, 17],
       [ 6, 18],
       [ 7, 19],
       [ 8, 20],
       [ 9, 21],
       [10, 22],
       [11, 23],
       [12, 24]])

In [136]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(9,15).reshape(2,3)

In [139]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [138]:
c = np.stack((a,b))
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 9, 10, 11],
        [12, 13, 14]]])

In [140]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(9,15).reshape(2,3)

In [141]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 9 10 11]
 [12 13 14]]


In [144]:
c = np.stack((a,b),axis=0)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 9, 10, 11],
        [12, 13, 14]]])

In [145]:
c = np.stack((a,b),axis=1)
c

array([[[ 1,  2,  3],
        [ 9, 10, 11]],

       [[ 4,  5,  6],
        [12, 13, 14]]])

In [146]:
a = np.arange(1,13).reshape(2,3,2)
b = np.arange(13,25).reshape(2,3,2)

In [147]:
np.stack((a,b))

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16],
         [17, 18]],

        [[19, 20],
         [21, 22],
         [23, 24]]]])

In [151]:
a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [150]:
np.min(a,axis=1)

array([1, 5, 9])

In [152]:
np.max(a,axis=0)

array([ 9, 10, 11, 12])

In [157]:
a = np.array([1,2,4,5,675,2,2,35,6,90])
a

array([  1,   2,   4,   5, 675,   2,   2,  35,   6,  90])

In [158]:
c = np.argsort(a)
c

array([0, 1, 6, 5, 2, 3, 8, 7, 9, 4])

In [162]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [164]:
np.argsort(a,axis=0)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [ ]:
np.argmin(a,axis=0)

array([0, 0, 0, 0])

In [167]:
np.argmax(a,axis=1)

array([3, 3, 3])

In [170]:
a = [1.54,4,565,6.67,7,8.9887]

b = np.array(a)

In [176]:
print(np.floor(a))
print(np.round(a,2))

[  1.   4. 565.   6.   7.   8.]
[  1.54   4.   565.     6.67   7.     8.99]


In [180]:
a = np.array([1,2,3])
b = np.array([[1],[2]])

print(a)
print(b)

[1 2 3]
[[1]
 [2]]


In [179]:
a+b

array([[2, 3, 4],
       [3, 4, 5]])

In [181]:
a = np.arange(6).reshape(2,3)
b = np.array([[0,1],[1,2]])

print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [1 2]]


In [183]:
a[[0,1],[1,2]]

array([1, 5])

In [185]:
a[:,[1,2]]

array([[1, 2],
       [4, 5]])

In [189]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [190]:
a[1,2]

np.int64(6)

In [192]:
a[[1,1]]

array([[4, 5, 6],
       [4, 5, 6]])

In [194]:
a = np.arange(1,6)
b = np.arange(7,9)

a+b

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [196]:
a = np.array([1,2,3,4])

In [199]:
b = a[[0,2]]

In [200]:
b[0] = 99

In [201]:
print(a)
print(b)

[1 2 3 4]
[99  3]


In [207]:
a = np.arange(1,7).reshape(2,3)
b = a[:,1]

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[2 5]


In [205]:
b[0] = 100

In [206]:
print(a)
print(b)

[[  0 100   2]
 [  3   4   5]]
[100   4]


In [208]:
a[:,1]

array([2, 5])