In [1]:
import numpy as np

In [2]:
stock= np.random.randint(190,6762,(5,24))

In [3]:
stock

array([[4369, 4214, 3603, 1968, 3843, 6559, 3824, 3876, 3850, 3992,  997,
        1402, 2488, 4860, 2311, 5167, 6486, 6409, 5229, 5079, 3270,  960,
        1317, 5055],
       [ 356, 6405, 3089,  852, 2201,  213, 3922, 3007, 3985, 6668, 4629,
        3332,  647, 3486, 4946, 3937, 2772,  595, 5679,  979, 4405, 2789,
         648, 4374],
       [3769, 4684, 1701, 2729, 2355, 4719, 1536, 3874, 6332, 1969, 3448,
         365, 5332, 3093,  588,  830, 6659, 5655, 1011, 1474, 1277, 1702,
         872,  785],
       [6171, 5559, 5260, 2562, 2622, 4985,  699, 6043, 5758, 6505, 1255,
         269, 1174, 3866,  940,  775, 4886, 6472, 5476, 3476, 3787, 6199,
        2365, 2898],
       [1466, 1642, 1216, 2475,  920,  897, 6395, 6248, 1419, 5674, 6353,
        6122, 5601, 6391, 1438, 1824, 1129, 2985, 2397, 2045, 6338, 2542,
        3681, 4792]], dtype=int32)

In [4]:
#number of days and hours
days, hours = stock.shape
days,hours

(5, 24)

In [5]:
#find the number of dimennsions
stock.ndim

2

In [6]:
#find the datatype of the stock prices

stock.dtype

dtype('int32')

In [7]:
#indexing and slicing

# get all prices of day 2

stock[1:2,::]

array([[ 356, 6405, 3089,  852, 2201,  213, 3922, 3007, 3985, 6668, 4629,
        3332,  647, 3486, 4946, 3937, 2772,  595, 5679,  979, 4405, 2789,
         648, 4374]], dtype=int32)

In [8]:
#get the prices of day 4 from 9am to 3pm

stock[3:4,8:15]

array([[5758, 6505, 1255,  269, 1174, 3866,  940]], dtype=int32)

In [9]:
#get the price of day 3 hour 12

stock[2:3,11:12]

array([[365]], dtype=int32)

In [10]:
#increase all the prices by 2%

stock_increased = stock*1.2
stock_increased

array([[5242.8, 5056.8, 4323.6, 2361.6, 4611.6, 7870.8, 4588.8, 4651.2,
        4620. , 4790.4, 1196.4, 1682.4, 2985.6, 5832. , 2773.2, 6200.4,
        7783.2, 7690.8, 6274.8, 6094.8, 3924. , 1152. , 1580.4, 6066. ],
       [ 427.2, 7686. , 3706.8, 1022.4, 2641.2,  255.6, 4706.4, 3608.4,
        4782. , 8001.6, 5554.8, 3998.4,  776.4, 4183.2, 5935.2, 4724.4,
        3326.4,  714. , 6814.8, 1174.8, 5286. , 3346.8,  777.6, 5248.8],
       [4522.8, 5620.8, 2041.2, 3274.8, 2826. , 5662.8, 1843.2, 4648.8,
        7598.4, 2362.8, 4137.6,  438. , 6398.4, 3711.6,  705.6,  996. ,
        7990.8, 6786. , 1213.2, 1768.8, 1532.4, 2042.4, 1046.4,  942. ],
       [7405.2, 6670.8, 6312. , 3074.4, 3146.4, 5982. ,  838.8, 7251.6,
        6909.6, 7806. , 1506. ,  322.8, 1408.8, 4639.2, 1128. ,  930. ,
        5863.2, 7766.4, 6571.2, 4171.2, 4544.4, 7438.8, 2838. , 3477.6],
       [1759.2, 1970.4, 1459.2, 2970. , 1104. , 1076.4, 7674. , 7497.6,
        1702.8, 6808.8, 7623.6, 7346.4, 6721.2, 7669.2, 1725

In [11]:
#compare prices are greater than 1400

stock_increased > 1400


array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True],
       [False,  True,  True, False,  True, False,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True, False,
         True, False,  True,  True, False,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True, False, False,  True,  True,
        False,  True,  True,  True, False, False],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True, False,  True,  True, False, False,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True]])

In [12]:
stock

array([[4369, 4214, 3603, 1968, 3843, 6559, 3824, 3876, 3850, 3992,  997,
        1402, 2488, 4860, 2311, 5167, 6486, 6409, 5229, 5079, 3270,  960,
        1317, 5055],
       [ 356, 6405, 3089,  852, 2201,  213, 3922, 3007, 3985, 6668, 4629,
        3332,  647, 3486, 4946, 3937, 2772,  595, 5679,  979, 4405, 2789,
         648, 4374],
       [3769, 4684, 1701, 2729, 2355, 4719, 1536, 3874, 6332, 1969, 3448,
         365, 5332, 3093,  588,  830, 6659, 5655, 1011, 1474, 1277, 1702,
         872,  785],
       [6171, 5559, 5260, 2562, 2622, 4985,  699, 6043, 5758, 6505, 1255,
         269, 1174, 3866,  940,  775, 4886, 6472, 5476, 3476, 3787, 6199,
        2365, 2898],
       [1466, 1642, 1216, 2475,  920,  897, 6395, 6248, 1419, 5674, 6353,
        6122, 5601, 6391, 1438, 1824, 1129, 2985, 2397, 2045, 6338, 2542,
        3681, 4792]], dtype=int32)

In [13]:
#find the highest price per day

np.max(stock, axis=1)

array([6559, 6668, 6659, 6505, 6395], dtype=int32)

In [14]:
#find the average stock price at each hour across all 5 day

np.mean(stock,axis=0)

array([3226.2, 4500.8, 2973.8, 2117.2, 2388.2, 3474.6, 3275.2, 4609.6,
       4268.8, 4961.6, 3336.4, 2298. , 3048.4, 4339.2, 2044.6, 2506.6,
       4386.4, 4423.2, 3958.4, 2610.6, 3815.4, 2838.4, 1776.6, 3580.8])

In [15]:
#find the overall max, min, mean, variance, and standard deviation for the week

np.max(stock).item()

6668

In [16]:
np.min(stock).item()

213

In [17]:
np.mean(stock).item()

3364.9583333333335

In [21]:
np.var(stock).item()

3898153.506597222

In [20]:
np.std(stock).item()

1974.3742063239233